#@data/values
---
environment: prod #! set this to 'local' or 'prod'
os: linux #! set this to 'linux', 'mac' or 'windows'
email: square@example.com #! add your email here to obtain certifcates from let's encrypt
tag: latest

skills:
  - name: boolq
    author: ukp
  - name: commonsense-qa
    author: ukp
  - name: extractive-qa
    author: ukp
  - name: generative-qa
    author: ukp
  - name: multiple-choice-qa
    author: ukp
  - name: open-extractive-qa
    author: ukp
  - name: qa-gnn
    author: ukp
  - name: information-retrieval
    author: ukp
  - name: tweac
    author: ukp

web_concurrency: 2

verify_ssl:
  prod: 1
  local: 0

verify_issuer:
  prod: 1
  local: 0

realm: square

square_api_url: 
  prod: https://square.ukp-lab.de/api
  local: https://host.docker.internal/api

keycloak_base_url:
  prod: square.ukp-lab.de
  local: square.ukp-lab.localhost

frontend_url:
  prod: square.ukp-lab.de
  local: square.ukp-lab.localhost

keycloak_base_url_https:
  prod: https://square.ukp-lab.de
  local: http://keycloak:8080

faiss_url:
  prod: https://square.ukp-lab.de/api
  local: https://localhost/api

model_url:
  prod: https://square.ukp-lab.de/api
  local: https://localhost/api

docker_host_url:
  windows: http://host.docker.internal
  mac: http://host.docker.internal
  linux: https://172.17.0.1
